bringing in java_opts and sbt home dir

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -39,49 +39,42 @@ install_java ${BUILD_DIR} ${javaVersion}
 jdk_overlay ${BUILD_DIR}
 echo "done"
 
+# home directory from perspective of SBT; we rename
+# it because otherwise the project root and $HOME
+# are the same, and by default .sbt has a (different)
+# meaning in those two places
+SBT_USER_HOME=".sbt_home"
+SBT_USER_HOME_ABSOLUTE="$BUILD_DIR/$SBT_USER_HOME"
+
 cd $BUILD_DIR
-#
-# # unpack cache
-# CACHED_DIRS="$SBT_USER_HOME/.ivy2 $SBT_BINDIR target project/target project/boot"
-# for DIR in $CACHED_DIRS; do
-#   cache_copy $DIR $CACHE_DIR $BUILD_DIR
-# done
-#
-# if [ ! -d .ivy2/cache ]; then
-#   mkdir -p .ivy2/cache
-# fi
 
-echo -n "-----> Compiling Application... "
-./activator clean stage
+ACTIVATOR_TASKS="stage"
 
-#
-# PROFILE_PATH="$BUILD_DIR/.profile.d/scala.sh"
-# mkdir -p $(dirname $PROFILE_PATH)
-# echo 'export PATH="/app/.jdk/bin:$PATH"' >> $PROFILE_PATH
-#
-# # repack cache
-# mkdir -p $CACHE_DIR
-# for DIR in $CACHED_DIRS; do
-# cache_copy $DIR $BUILD_DIR $CACHE_DIR
-# done
-#
-# # drop useless directories from slug for play only
-# if is_play $BUILD_DIR ; then
-# if [ -d $SBT_USER_HOME/.ivy2 ]; then
-# echo "-----> Dropping ivy cache from the slug"
-#     rm -rf $SBT_USER_HOME/.ivy2
-#   fi
-# if [ -d $BUILD_DIR/project/boot ] ; then
-# echo "-----> Dropping project boot dir from the slug"
-#     rm -rf $BUILD_DIR/project/boot
-#   fi
-# if [ -d $BUILD_DIR/target ] ; then
-# echo "-----> Dropping compilation artifacts from the slug"
-#     rm -rf $BUILD_DIR/target/scala-*
-#     rm -rf $BUILD_DIR/target/streams
-#     rm -rf $BUILD_DIR/target/resolution-cache
-#   fi
-# fi
+# To enable clean compiles, configure the environment to clean:
+# $ heroku config:set ACTIVATOR_CLEAN=true
+# $ git push heroku master
+# See: https://devcenter.heroku.com/articles/scala-support#clean-builds
+[ "$ACTIVATOR_CLEAN" = "true" ] && ACTIVATOR_TASKS="clean $ACTIVATOR_TASKS"
+
+# copy in heroku sbt plugin
+# HEROKU_PLUGIN="HerokuPlugin.scala"
+# mkdir -p "$SBT_USER_HOME/.sbt/plugins"
+# cp -p $OPT_DIR/$HEROKU_PLUGIN $SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGIN
+
+JAVA_OPTS="-Xms768M -Xmx10M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled"
+JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF8 -Dsbt.log.noformat=true"
+JAVA_OPTS="$JAVA_OPTS -Duser.home=$SBT_USER_HOME_ABSOLUTE"
+JAVA_OPTS="$JAVA_OPTS -Divy.default.ivy.user.dir=$SBT_USER_HOME_ABSOLUTE/.ivy2"
+JAVA_OPTS="$JAVA_OPTS -Dsbt.global.base=$SBT_USER_HOME_ABSOLUTE"
+
+echo -n "-----> Running: activator $ACTIVATOR_TASKS"
+HOME="$SBT_USER_HOME_ABSOLUTE" ./activator $ACTIVATOR_TASKS 2>&1 | sed -u 's/^/       /'
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+echo " ! Failed to build app with sbt"
+  exit 1
+fi
+
+clean_play_slug $BUILD_DIR $SBT_USER_HOME
 
 # Move compiled app back to where Heroku expects it
 mv $BUILD_DIR $APP_BUILD_DIR
