trying to get the compile command working with the test-app

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -62,24 +62,19 @@ ACTIVATOR_TASKS="stage"
 # See: https://devcenter.heroku.com/articles/scala-support#clean-builds
 [ "$ACTIVATOR_CLEAN" = "true" ] && ACTIVATOR_TASKS="clean $ACTIVATOR_TASKS"
 
-# # copy in heroku sbt plugin
-# # HEROKU_PLUGIN="HerokuPlugin.scala"
-# # mkdir -p "$SBT_USER_HOME/.sbt/plugins"
-# # cp -p $OPT_DIR/$HEROKU_PLUGIN $SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGIN
-#
-# JAVA_OPTS="-Xms768M -Xmx1024M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled"
-# JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF8 -Dsbt.log.noformat=true"
-# JAVA_OPTS="$JAVA_OPTS -Duser.home=$SBT_USER_HOME_ABSOLUTE"
-# JAVA_OPTS="$JAVA_OPTS -Divy.default.ivy.user.dir=$SBT_USER_HOME_ABSOLUTE/.ivy2"
-# JAVA_OPTS="$JAVA_OPTS -Dsbt.global.base=$SBT_USER_HOME_ABSOLUTE"
-#
-# echo -n "-----> Running: activator $ACTIVATOR_TASKS" && echo ""
-# HOME="$SBT_USER_HOME_ABSOLUTE" JAVA_OPTS="$JAVA_OPTS" ./activator $ACTIVATOR_TASKS 2>&1 | sed -u 's/^/       /'
-# if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-# echo " ! Failed to build app with sbt"
-#   exit 1
-# fi
-#
+JAVA_OPTS="-Xms768M -Xmx1024M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled"
+JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF8 -Dsbt.log.noformat=true"
+JAVA_OPTS="$JAVA_OPTS -Duser.home=$SBT_USER_HOME_ABSOLUTE"
+JAVA_OPTS="$JAVA_OPTS -Divy.default.ivy.user.dir=$SBT_USER_HOME_ABSOLUTE/.ivy2"
+JAVA_OPTS="$JAVA_OPTS -Dsbt.global.base=$SBT_USER_HOME_ABSOLUTE"
+
+echo -n "-----> Running: activator $ACTIVATOR_TASKS" && echo ""
+HOME="$SBT_USER_HOME_ABSOLUTE" JAVA_OPTS="$JAVA_OPTS" ./activator $ACTIVATOR_TASKS 2>&1 | sed -u 's/^/       /'
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+echo " ! Failed to build app with sbt"
+  exit 1
+fi
+
 # # repack cache
 # mkdir -p $CACHE_DIR
 # for DIR in $CACHED_DIRS; do
